// angular-frontend/src/app/primegenerator/primegenerator.component.ts
import {Component, Injectable, OnInit} from '@angular/core';
import {FormControl, FormGroup} from "@angular/forms";
import {ApiService} from "../api.service";

@Component({
  selector: 'app-primegenerator',
  templateUrl: './primegenerator.component.html',
  styleUrls: ['./primegenerator.component.css']
})

@Injectable()
export class PrimegeneratorComponent implements OnInit {

  primeForm = new FormGroup({
    bitLength: new FormControl(),
    primeNumber: new FormControl()
  });

  constructor(private service: ApiService) {
  }

  ngOnInit(): void {
  }

  onSubmit() {
    this.service.getRandomPrime(this.primeForm.value.bitLength)
      .subscribe(data => {
        this.primeForm.patchValue({primeNumber: data});
      });
  }
}


<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1>Prime Generator</h1>
    <p>Requests a random number from the backend that is probable prime</p>
    <form [formGroup]="primeForm" (ngSubmit)="onSubmit()">
      <div>
        <label>BitLength:</label><br>
        <input type="text" class="form-control w-25" placeholder="32" formControlName="bitLength" value="32"/>
      </div>
      <div>
        <label>Prime number:</label><br>
        <textarea class="form-control" rows="5" readonly formControlName="primeNumber"></textarea><br>
        <input type="submit" value="Request random prime" class="btn btn-primary"/>
      </div>
    </form>
  </div>
</div>

// react-frontend/src/component/PrimeGenerator.js
import React from 'react'

class PrimeGenerator extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            bitLength: "",
            prime: ""
        };

        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleChange(event) {
        this.setState({bitLength: event.target.value});
    }

    handleSubmit(event) {
        this.randomPrimeFromBackend(this.state.bitLength);
        event.preventDefault();
    }

    randomPrimeFromBackend(bitLength) {
        fetch('http://localhost:8080/api/probable-prime?bitLength=' + bitLength)
            .then(res => res.text())
            .then(data => {
                this.setState({
                    prime: data
                })
            })
            .catch(console.log)
    }

    render() {
        return (
            <div className="row">
                <div className="col-md-8 offset-md-2">
                    <h2>Prime Generator</h2>
                    <p>Requests a random number from the backend that is probable prime</p>
                    <form onSubmit={this.handleSubmit}>
                        <div>
                            <label htmlFor="bitLength">Bit Length:</label>
                            <input type="text" value={this.state.bitLength} onChange={this.handleChange} id="bitLength"
                                   className="form-control w-25" placeholder="32"/>
                        </div>
                        <div>
                            <label htmlFor="prime">Prime number:</label>
                            <textarea className="form-control" rows="5" id="prime" value={this.state.prime} readOnly/>
                        </div>
                        <br/>
                        <input type="submit" value="Request random prime" className="btn btn-primary"/>
                    </form>
                </div>
            </div>
        )
    }
}


export default PrimeGenerator
